apiVersion: batch/v1
kind: CronJob
metadata:
  name: app
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: mood-detector
            imagePullPolicy: Never
          restartPolicy: Never
