version: "3"
services:
  gather-mood:
    image: gather-mood
    container_name: gather-mood
    restart: always
    environment:
      SUBREDDIT: "r/CryptoCurrency"

  redis:
    image: redis:7.0.0
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /mnt/data:/data
